openapi: 3.0.0
info:
  title: Serverless API
  version: 1.0.0

paths:
  /hello:
    get:
      summary: Returns a serverless response
      responses:
        '200':
          description: Successful response
